// Code generated by stripe-terraform generator. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/stripe/stripe-go/v84"
)

// ResourceWebhookEndpoint returns the schema for the stripe_webhook_endpoint resource
func ResourceWebhookEndpoint() *schema.Resource {
	return &schema.Resource{
		Description: "You can configure [webhook endpoints](https://docs.stripe.com/webhooks/) via the API to be notified about events that happen in your Stripe account or connected accounts. Most users configure webhooks from [the dashboard](https://dashboard.stripe.com/webhooks), which provides a user interface for registering and testing your webhook endpoints. Related guide: [Setting up webhooks](https://docs.stripe.com/webhooks/configure)",

		Schema: map[string]*schema.Schema{
			"id": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"api_version": {
				Type:        schema.TypeString,
				Description: "Events sent to this endpoint will be generated with this Stripe Version instead of your account's default Stripe Version.",
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
					"2011-01-01",
					"2011-06-21",
					"2011-06-28",
					"2011-08-01",
					"2011-09-15",
					"2011-11-17",
					"2012-02-23",
					"2012-03-25",
					"2012-06-18",
					"2012-06-28",
					"2012-07-09",
					"2012-09-24",
					"2012-10-26",
					"2012-11-07",
					"2013-02-11",
					"2013-02-13",
					"2013-07-05",
					"2013-08-12",
					"2013-08-13",
					"2013-10-29",
					"2013-12-03",
					"2014-01-31",
					"2014-03-13",
					"2014-03-28",
					"2014-05-19",
					"2014-06-13",
					"2014-06-17",
					"2014-07-22",
					"2014-07-26",
					"2014-08-04",
					"2014-08-20",
					"2014-09-08",
					"2014-10-07",
					"2014-11-05",
					"2014-11-20",
					"2014-12-08",
					"2014-12-17",
					"2014-12-22",
					"2015-01-11",
					"2015-01-26",
					"2015-02-10",
					"2015-02-16",
					"2015-02-18",
					"2015-03-24",
					"2015-04-07",
					"2015-06-15",
					"2015-07-07",
					"2015-07-13",
					"2015-07-28",
					"2015-08-07",
					"2015-08-19",
					"2015-09-03",
					"2015-09-08",
					"2015-09-23",
					"2015-10-01",
					"2015-10-12",
					"2015-10-16",
					"2016-02-03",
					"2016-02-19",
					"2016-02-22",
					"2016-02-23",
					"2016-02-29",
					"2016-03-07",
					"2016-06-15",
					"2016-07-06",
					"2016-10-19",
					"2017-01-27",
					"2017-02-14",
					"2017-04-06",
					"2017-05-25",
					"2017-06-05",
					"2017-08-15",
					"2017-12-14",
					"2018-01-23",
					"2018-02-05",
					"2018-02-06",
					"2018-02-28",
					"2018-05-21",
					"2018-07-27",
					"2018-08-23",
					"2018-09-06",
					"2018-09-24",
					"2018-10-31",
					"2018-11-08",
					"2019-02-11",
					"2019-02-19",
					"2019-03-14",
					"2019-05-16",
					"2019-08-14",
					"2019-09-09",
					"2019-10-08",
					"2019-10-17",
					"2019-11-05",
					"2019-12-03",
					"2020-03-02",
					"2020-08-27",
					"2022-08-01",
					"2022-11-15",
					"2023-08-16",
					"2023-10-16",
					"2024-04-10",
					"2024-06-20",
					"2024-09-30.acacia",
					"2024-10-28.acacia",
					"2024-11-20.acacia",
					"2024-12-18.acacia",
					"2025-01-27.acacia",
					"2025-02-24.acacia",
					"2025-03-01.dashboard",
					"2025-03-31.basil",
					"2025-04-30.basil",
					"2025-05-28.basil",
					"2025-06-30.basil",
					"2025-07-30.basil",
					"2025-08-27.basil",
					"2025-09-30.clover",
					"2025-10-29.clover",
					"2025-11-17.clover",
					"2026-03-25.dahlia",
					"2026-04-22.dahlia",
					"2026-05-27.dahlia",
				}, false)),
			},
			"connect": {
				Type:        schema.TypeBool,
				Description: "Whether this endpoint should receive events from connected accounts (`true`), or from your account (`false`). Defaults to `false`.",
				Optional:    true,
				Default:     false,
				ForceNew:    true,
			},
			"description": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},
			"enabled_events": {
				Type:        schema.TypeList,
				Description: "The list of events to enable for this endpoint. You may specify `['*']` to enable all events, except those that require explicit selection.",
				Required:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"metadata": {
				Type:     schema.TypeMap,
				Optional: true,
				Computed: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
			},
			"url": {
				Type:        schema.TypeString,
				Description: "The URL of the webhook endpoint.",
				Required:    true,
			},
			"application": {
				Type:        schema.TypeString,
				Description: "The ID of the associated Connect application.",
				Computed:    true,
			},
			"secret": {
				Type:        schema.TypeString,
				Description: "The endpoint's secret, used to generate [webhook signatures](https://docs.stripe.com/webhooks/signatures). Only returned at creation.",
				Computed:    true,
				Sensitive:   true,
			},
			"status": {
				Type:        schema.TypeString,
				Description: "The status of the webhook. It can be `enabled` or `disabled`.",
				Computed:    true,
			},
		},

		CreateContext: resourceWebhookEndpointCreate,
		ReadContext:   resourceWebhookEndpointRead,
		UpdateContext: resourceWebhookEndpointUpdate,
		DeleteContext: resourceWebhookEndpointDelete,

		Importer: &schema.ResourceImporter{
			StateContext: resourceWebhookEndpointImportState,
		},
	}
}

func resourceWebhookEndpointCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Creating stripe_webhook_endpoint resource")
	c := meta.(*stripe.Client)

	params := &stripe.WebhookEndpointCreateParams{}

	if v, ok := d.Get("api_version").(string); ok && v != "" {
		params.APIVersion = stripe.String(v)
	}
	params.Connect = stripe.Bool(d.Get("connect").(bool))
	if v, ok := d.Get("description").(string); ok && v != "" {
		params.Description = stripe.String(v)
	}
	if v, ok := d.Get("enabled_events").([]interface{}); ok && len(v) > 0 {
		strArr := make([]*string, len(v))
		for i, item := range v {
			if s, ok := item.(string); ok {
				strArr[i] = stripe.String(s)
			}
		}
		params.EnabledEvents = strArr
	}
	if v, ok := d.Get("metadata").(map[string]interface{}); ok && len(v) > 0 {
		params.Metadata = make(map[string]string)
		for k, val := range v {
			params.Metadata[k] = val.(string)
		}
	}
	if v, ok := d.Get("url").(string); ok && v != "" {
		params.URL = stripe.String(v)
	}
	webhook_endpoint, err := c.V1WebhookEndpoints.Create(ctx, params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to create webhook_endpoint: %w", err))
	}

	d.SetId(webhook_endpoint.ID)
	diags := resourceWebhookEndpointRead(ctx, d, meta)

	if err := d.Set("secret", webhook_endpoint.Secret); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	return diags
}

func resourceWebhookEndpointRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	importing := ctx.Value("importing") != nil
	_ = importing
	tflog.Debug(ctx, "Reading stripe_webhook_endpoint resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	webhook_endpoint, err := c.V1WebhookEndpoints.Retrieve(ctx, d.Id(), nil)
	if err != nil {
		// Check if it's a 404 (resource was deleted) vs other errors
		if stripeErr, ok := err.(*stripe.Error); ok && stripeErr.HTTPStatusCode == 404 {
			// Resource was deleted
			d.SetId("")
			return diags
		}
		// Other errors should be returned as diagnostics
		return diag.FromErr(fmt.Errorf("failed to read webhook_endpoint: %w", err))
	}

	if err := d.Set("api_version", webhook_endpoint.APIVersion); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("description", webhook_endpoint.Description); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if webhook_endpoint.EnabledEvents != nil && len(webhook_endpoint.EnabledEvents) > 0 {
		if err := d.Set("enabled_events", webhook_endpoint.EnabledEvents); err != nil {
			diags = append(diags, diag.FromErr(err)...)
		}
	}
	if err := d.Set("metadata", webhook_endpoint.Metadata); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("url", webhook_endpoint.URL); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("application", webhook_endpoint.Application); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("status", webhook_endpoint.Status); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	return diags
}

func resourceWebhookEndpointUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Updating stripe_webhook_endpoint resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.WebhookEndpointUpdateParams{}

	if d.HasChange("description") {
		if v, ok := d.Get("description").(string); ok && v != "" {
			params.Description = stripe.String(v)
		}
	}
	if d.HasChange("enabled_events") {
		if v, ok := d.Get("enabled_events").([]interface{}); ok && len(v) > 0 {
			strArr := make([]*string, len(v))
			for i, item := range v {
				if s, ok := item.(string); ok {
					strArr[i] = stripe.String(s)
				}
			}
			params.EnabledEvents = strArr
		}
	}
	if d.HasChange("metadata") {
		// Handle metadata updates including deletions
		old, new := d.GetChange("metadata")
		oldMap := make(map[string]string)
		if old != nil {
			if oldMeta, ok := old.(map[string]interface{}); ok {
				for k, v := range oldMeta {
					oldMap[k] = v.(string)
				}
			}
		}
		params.Metadata = make(map[string]string)
		// Add/update keys from new metadata
		if new != nil {
			if newMeta, ok := new.(map[string]interface{}); ok {
				for k, v := range newMeta {
					params.Metadata[k] = v.(string)
				}
			}
		}
		// Mark removed keys for deletion by setting to empty string
		for k := range oldMap {
			if _, exists := params.Metadata[k]; !exists {
				params.Metadata[k] = ""
			}
		}
	}
	if d.HasChange("url") {
		if v, ok := d.Get("url").(string); ok && v != "" {
			params.URL = stripe.String(v)
		}
	}
	// Skip update if no fields were actually changed
	// This handles cases where fields are removed from config (HasChange returns true but new value is empty)
	if !paramsHasFields(params) {
		return resourceWebhookEndpointRead(ctx, d, meta)
	}

	_, err := c.V1WebhookEndpoints.Update(ctx, d.Id(), params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to update webhook_endpoint: %w", err))
	}

	return resourceWebhookEndpointRead(ctx, d, meta)
}

func resourceWebhookEndpointDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Deleting stripe_webhook_endpoint resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	_, err := c.V1WebhookEndpoints.Delete(ctx, d.Id(), nil)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to delete webhook_endpoint: %w", err))
	}

	d.SetId("")
	return nil
}

func resourceWebhookEndpointImportState(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	diags := resourceWebhookEndpointRead(context.WithValue(ctx, "importing", true), d, meta)
	if diags.HasError() {
		return nil, fmt.Errorf("%s", diags[0].Summary)
	}

	return []*schema.ResourceData{d}, nil
}
